const meals = [
        { name: "Oatmeal with Banana", fiber: 4, calories: 150, protein: 5, sugar: 12, fat: 3, vitamins: 10, ingredients: { "Oats (g)": 50, "Banana (g)": 100 } },
        { name: "Chicken Salad", fiber: 6, calories: 300, protein: 25, sugar: 3, fat: 15, vitamins: 20, ingredients: { "Chicken Breast (g)": 150, "Lettuce (g)": 100, "Tomatoes (g)": 50 } },
        { name: "Grilled Salmon with Veggies", fiber: 5, calories: 350, protein: 35, sugar: 2, fat: 20, vitamins: 25, ingredients: { "Salmon (g)": 200, "Broccoli (g)": 100, "Carrots (g)": 50 } },
        { name: "Vegetable Stir Fry", fiber: 7, calories: 200, protein: 5, sugar: 8, fat: 10, vitamins: 18, ingredients: { "Mixed Vegetables (g)": 150, "Soy Sauce (g)": 20, "Olive Oil (g)": 10 } },
        { name: "Avocado Toast", fiber: 5, calories: 250, protein: 8, sugar: 2, fat: 15, vitamins: 30, ingredients: { "Whole Wheat Bread (g)": 50, "Avocado (g)": 100 } },
        { name: "Egg White Omelette", fiber: 1, calories: 120, protein: 15, sugar: 2, fat: 4, vitamins: 15, ingredients: { "Egg Whites (g)": 150, "Spinach (g)": 50, "Olive Oil (g)": 10 } },
        { name: "Greek Yogurt with Berries", fiber: 4, calories: 180, protein: 15, sugar: 14, fat: 5, vitamins: 12, ingredients: { "Greek Yogurt (g)": 150, "Mixed Berries (g)": 100 } },
        { name: "Quinoa Salad", fiber: 8, calories: 350, protein: 12, sugar: 6, fat: 10, vitamins: 20, ingredients: { "Quinoa (g)": 100, "Chickpeas (g)": 50, "Cucumber (g)": 50 } },
        { name: "Smoothie Bowl", fiber: 6, calories: 250, protein: 5, sugar: 18, fat: 8, vitamins: 35, ingredients: { "Banana (g)": 100, "Spinach (g)": 50, "Almond Milk (g)": 200 } },
        { name: "Tuna Salad", fiber: 4, calories: 300, protein: 35, sugar: 3, fat: 15, vitamins: 10, ingredients: { "Canned Tuna (g)": 150, "Lettuce (g)": 50, "Olive Oil (g)": 10 } },
        { name: "Pasta Primavera", fiber: 7, calories: 400, protein: 12, sugar: 8, fat: 15, vitamins: 25, ingredients: { "Whole Wheat Pasta (g)": 100, "Mixed Vegetables (g)": 150, "Parmesan Cheese (g)": 20 } },
        { name: "Cottage Cheese with Fruit", fiber: 3, calories: 180, protein: 15, sugar: 12, fat: 4, vitamins: 10, ingredients: { "Cottage Cheese (g)": 150, "Apple (g)": 100 } },
        { name: "Turkey and Avocado Wrap", fiber: 5, calories: 350, protein: 30, sugar: 4, fat: 18, vitamins: 20, ingredients: { "Whole Wheat Wrap (g)": 50, "Turkey Breast (g)": 100, "Avocado (g)": 50 } },
        { name: "Beef Stir Fry", fiber: 4, calories: 400, protein: 30, sugar: 3, fat: 20, vitamins: 15, ingredients: { "Beef (g)": 150, "Bell Peppers (g)": 100, "Soy Sauce (g)": 20 } },
        { name: "Chicken Tacos", fiber: 6, calories: 350, protein: 30, sugar: 2, fat: 12, vitamins: 20, ingredients: { "Chicken (g)": 150, "Corn Tortillas (g)": 50, "Lettuce (g)": 50 } },
        { name: "Chickpea Curry", fiber: 9, calories: 300, protein: 15, sugar: 8, fat: 10, vitamins: 30, ingredients: { "Chickpeas (g)": 150, "Tomato Sauce (g)": 100, "Spinach (g)": 50 } },
        { name: "Grilled Chicken with Asparagus", fiber: 5, calories: 350, protein: 40, sugar: 3, fat: 10, vitamins: 15, ingredients: { "Chicken Breast (g)": 200, "Asparagus (g)": 100 } },
        { name: "Sweet Potato and Black Bean Bowl", fiber: 8, calories: 350, protein: 12, sugar: 4, fat: 8, vitamins: 25, ingredients: { "Sweet Potato (g)": 150, "Black Beans (g)": 100, "Avocado (g)": 50 } },
        { name: "Mango Chicken Salad", fiber: 6, calories: 280, protein: 25, sugar: 12, fat: 15, vitamins: 30, ingredients: { "Chicken (g)": 150, "Mango (g)": 100, "Lettuce (g)": 50 } },
        { name: "Lentil Soup", fiber: 8, calories: 300, protein: 18, sugar: 5, fat: 6, vitamins: 20, ingredients: { "Lentils (g)": 150, "Carrots (g)": 100, "Tomato Sauce (g)": 50 } },
        { name: "Spaghetti with Marinara", fiber: 5, calories: 350, protein: 10, sugar: 8, fat: 12, vitamins: 18, ingredients: { "Whole Wheat Spaghetti (g)": 100, "Tomato Sauce (g)": 150, "Garlic (g)": 10 } },
        { name: "Eggplant Parmesan", fiber: 6, calories: 280, protein: 12, sugar: 8, fat: 14, vitamins: 20, ingredients: { "Eggplant (g)": 150, "Tomato Sauce (g)": 100, "Mozzarella Cheese (g)": 50 } },
        { name: "Chicken Fried Rice", fiber: 4, calories: 400, protein: 25, sugar: 6, fat: 18, vitamins: 25, ingredients: { "Chicken (g)": 150, "Brown Rice (g)": 100, "Mixed Vegetables (g)": 50 } },
        { name: "Salmon Tacos", fiber: 5, calories: 350, protein: 30, sugar: 3, fat: 15, vitamins: 20, ingredients: { "Salmon (g)": 150, "Corn Tortillas (g)": 50, "Cabbage (g)": 50 } },
        { name: "Zucchini Noodles with Pesto", fiber: 6, calories: 250, protein: 7, sugar: 4, fat: 15, vitamins: 25, ingredients: { "Zucchini (g)": 200, "Pesto Sauce (g)": 50, "Parmesan Cheese (g)": 20 } },
        { name: "Poke Bowl", fiber: 7, calories: 400, protein: 30, sugar: 5, fat: 12, vitamins: 15, ingredients: { "Tuna (g)": 150, "Brown Rice (g)": 100, "Avocado (g)": 50 } },
        { name: "Chia Pudding", fiber: 10, calories: 200, protein: 5, sugar: 5, fat: 10, vitamins: 18, ingredients: { "Chia Seeds (g)": 30, "Almond Milk (g)": 150, "Berries (g)": 50 } },
        { name: "Cauliflower Rice Stir Fry", fiber: 6, calories: 250, protein: 10, sugar: 6, fat: 10, vitamins: 20, ingredients: { "Cauliflower (g)": 150, "Mixed Vegetables (g)": 100, "Soy Sauce (g)": 20 } },
        { name: "Shrimp Salad", fiber: 4, calories: 350, protein: 30, sugar: 2, fat: 15, vitamins: 30, ingredients: { "Shrimp (g)": 150, "Lettuce (g)": 50, "Cucumber (g)": 50 } },
        { name: "Vegetable Soup", fiber: 6, calories: 180, protein: 6, sugar: 10, fat: 5, vitamins: 25, ingredients: { "Mixed Vegetables (g)": 150, "Tomato Sauce (g)": 100, "Vegetable Broth (g)": 200 } },
        { name: "Green Flame Chicken", fiber: 4, calories: 320, protein: 35, sugar: 2, fat: 14, vitamins: 90, ingredients: { "Chicken breast (g)": 150, "Broccoli (g)": 100, "Olive oil (g)": 10 } },
        { name: "Morning Crunch Toast", fiber: 5, calories: 270, protein: 10, sugar: 1, fat: 17, vitamins: 30, ingredients: { "Whole grain bread (g)": 40, "Egg (g)": 60, "Avocado (g)": 70 } },
        { name: "Berry Cloud Parfait", fiber: 2, calories: 180, protein: 12, sugar: 14, fat: 5, vitamins: 50, ingredients: { "Greek yogurt (g)": 150, "Strawberries (g)": 80, "Honey (g)": 10 } },
        { name: "Citrus Coast Salmon", fiber: 2, calories: 280, protein: 30, sugar: 0, fat: 15, vitamins: 120, ingredients: { "Salmon (g)": 150, "Spinach (g)": 100, "Lemon juice (g)": 10 } },
        { name: "Island Fuel Bowl", fiber: 5, calories: 270, protein: 8, sugar: 9, fat: 9, vitamins: 15, ingredients: { "Rolled oats (g)": 40, "Banana (g)": 100, "Peanut butter (g)": 15 } },
        { name: "Harbor Light Salad", fiber: 6, calories: 290, protein: 25, sugar: 2, fat: 11, vitamins: 10, ingredients: { "Tuna (g)": 100, "Chickpeas (g)": 100, "Olive oil (g)": 10 } },
        { name: "Golden Garden Scramble", fiber: 1, calories: 280, protein: 18, sugar: 1, fat: 20, vitamins: 60, ingredients: { "Eggs (g)": 120, "Cheddar cheese (g)": 30, "Spinach (g)": 50 } },
        { name: "Fiesta Flame Potato", fiber: 8, calories: 250, protein: 10, sugar: 7, fat: 1.5, vitamins: 140, ingredients: { "Sweet potato (g)": 150, "Black beans (g)": 100, "Salsa (g)": 50 } },
        { name: "Cinnamon Orchard Bites", fiber: 4, calories: 210, protein: 4, sugar: 14, fat: 10, vitamins: 12, ingredients: { "Apple (g)": 150, "Almond butter (g)": 20, "Cinnamon (g)": 2 } },
        { name: "Coastal Stir Bowl", fiber: 3, calories: 260, protein: 22, sugar: 3, fat: 2, vitamins: 70, ingredients: { "Shrimp (g)": 100, "Brown rice (g)": 100, "Bell pepper (g)": 80 } },
        { name: "Spiced Chickpea Delight", fiber: 7, calories: 240, protein: 12, sugar: 4, fat: 6, vitamins: 40, ingredients: { "Chickpeas (g)": 120, "Tomato sauce (g)": 80, "Olive oil (g)": 10 } },
        { name: "Rustic Beef & Greens", fiber: 3, calories: 310, protein: 28, sugar: 2, fat: 18, vitamins: 35, ingredients: { "Lean beef (g)": 150, "Kale (g)": 80, "Olive oil (g)": 10 } },
        { name: "Tropical Quinoa Bowl", fiber: 6, calories: 260, protein: 9, sugar: 8, fat: 7, vitamins: 50, ingredients: { "Quinoa (g)": 70, "Mango (g)": 90, "Avocado (g)": 50 } },
        { name: "Savory Eggplant Stack", fiber: 5, calories: 220, protein: 7, sugar: 5, fat: 10, vitamins: 30, ingredients: { "Eggplant (g)": 150, "Mozzarella (g)": 50, "Tomato sauce (g)": 60 } },
        { name: "Lemon Garlic Shrimp", fiber: 1, calories: 210, protein: 25, sugar: 1, fat: 7, vitamins: 20, ingredients: { "Shrimp (g)": 120, "Garlic (g)": 10, "Lemon juice (g)": 10 } },
        { name: "Hearty Lentil Soup", fiber: 8, calories: 230, protein: 14, sugar: 3, fat: 4, vitamins: 45, ingredients: { "Lentils (g)": 100, "Carrot (g)": 70, "Onion (g)": 40 } },
        { name: "Zesty Turkey Wrap", fiber: 4, calories: 280, protein: 27, sugar: 2, fat: 9, vitamins: 25, ingredients: { "Turkey breast (g)": 120, "Whole wheat wrap (g)": 60, "Spinach (g)": 30 } },
        { name: "Sweet Potato Toasties", fiber: 6, calories: 240, protein: 6, sugar: 6, fat: 5, vitamins: 100, ingredients: { "Sweet potato (g)": 150, "Almond butter (g)": 20, "Chia seeds (g)": 15 } },
        { name: "Garlic Herb Chicken", fiber: 2, calories: 310, protein: 33, sugar: 1, fat: 14, vitamins: 25, ingredients: { "Chicken breast (g)": 150, "Garlic (g)": 10, "Rosemary (g)": 5 } },
        { name: "Spicy Turkey Skillet", fiber: 3, calories: 320, protein: 30, sugar: 2, fat: 16, vitamins: 35, ingredients: { "Ground turkey (g)": 150, "Bell pepper (g)": 100, "Olive oil (g)": 10 } },
        { name: "Mango Black Bean Salad", fiber: 7, calories: 250, protein: 8, sugar: 9, fat: 5, vitamins: 60, ingredients: { "Black beans (g)": 100, "Mango (g)": 90, "Cilantro (g)": 10 } },
        { name: "Cocoa Banana Smoothie", fiber: 4, calories: 220, protein: 6, sugar: 15, fat: 4, vitamins: 20, ingredients: { "Banana (g)": 100, "Cocoa powder (g)": 15, "Greek yogurt (g)": 120 } },
        { name: "Honey Mustard Chicken", fiber: 2, calories: 300, protein: 32, sugar: 5, fat: 12, vitamins: 30, ingredients: { "Chicken breast (g)": 150, "Honey (g)": 15, "Mustard (g)": 10 } },
        { name: "Tomato Basil Pasta", fiber: 5, calories: 280, protein: 9, sugar: 6, fat: 7, vitamins: 40, ingredients: { "Pasta (g)": 100, "Tomato sauce (g)": 80, "Basil (g)": 10 } },
        { name: "Lentil Spinach Curry", fiber: 8, calories: 240, protein: 14, sugar: 3, fat: 6, vitamins: 50, ingredients: { "Lentils (g)": 100, "Spinach (g)": 80, "Coconut milk (g)": 40 } },
        { name: "Peanut Butter Apple Bites", fiber: 4, calories: 210, protein: 5, sugar: 13, fat: 10, vitamins: 15, ingredients: { "Apple (g)": 150, "Peanut butter (g)": 20, "Cinnamon (g)": 2 } },
        { name: "Crispy Tofu Stir Fry", fiber: 6, calories: 260, protein: 20, sugar: 4, fat: 10, vitamins: 45, ingredients: { "Tofu (g)": 120, "Broccoli (g)": 100, "Soy sauce (g)": 15 } },
        { name: "Sweet Chili Shrimp", fiber: 1, calories: 230, protein: 25, sugar: 5, fat: 8, vitamins: 20, ingredients: { "Shrimp (g)": 120, "Sweet chili sauce (g)": 20, "Garlic (g)": 10 } },
        { name: "Avocado Egg Salad", fiber: 5, calories: 290, protein: 15, sugar: 1, fat: 22, vitamins: 35, ingredients: { "Eggs (g)": 120, "Avocado (g)": 70, "Mayonnaise (g)": 15 } },
        { name: "Quinoa Veggie Medley", fiber: 7, calories: 270, protein: 10, sugar: 5, fat: 8, vitamins: 55, ingredients: { "Quinoa (g)": 70, "Zucchini (g)": 80, "Red bell pepper (g)": 50 } },
        { name: "Garlic Lemon Salmon", fiber: 1, calories: 290, protein: 30, sugar: 0, fat: 16, vitamins: 25, ingredients: { "Salmon (g)": 150, "Garlic (g)": 10, "Lemon juice (g)": 10 } },
        { name: "Banana Oat Pancakes", fiber: 4, calories: 250, protein: 7, sugar: 8, fat: 6, vitamins: 15, ingredients: { "Banana (g)": 100, "Oats (g)": 60, "Egg (g)": 60 } },
        { name: "Spiced Chickpea Wrap", fiber: 6, calories: 280, protein: 13, sugar: 3, fat: 7, vitamins: 40, ingredients: { "Chickpeas (g)": 120, "Whole wheat wrap (g)": 60, "Cumin (g)": 5 } },
        { name: "Honey Garlic Tofu", fiber: 4, calories: 250, protein: 18, sugar: 10, fat: 10, vitamins: 35, ingredients: { "Tofu (g)": 120, "Honey (g)": 15, "Garlic (g)": 10 } },
        { name: "Peach Cottage Cheese", fiber: 2, calories: 180, protein: 15, sugar: 9, fat: 4, vitamins: 10, ingredients: { "Cottage cheese (g)": 150, "Peach (g)": 80, "Honey (g)": 10 } },
        { name: "Mediterranean Tuna Salad", fiber: 4, calories: 310, protein: 28, sugar: 3, fat: 14, vitamins: 35, ingredients: { "Tuna (g)": 120, "Cucumber (g)": 80, "Olive oil (g)": 10 } },
        { name: "Pumpkin Spice Smoothie", fiber: 5, calories: 220, protein: 6, sugar: 12, fat: 5, vitamins: 40, ingredients: { "Pumpkin puree (g)": 100, "Greek yogurt (g)": 120, "Cinnamon (g)": 3 } },
        { name: "Sweet Potato & Black Bean", fiber: 8, calories: 270, protein: 12, sugar: 6, fat: 5, vitamins: 120, ingredients: { "Sweet potato (g)": 150, "Black beans (g)": 100, "Cilantro (g)": 10 } },
        { name: "Coconut Mango Chia Pudding", fiber: 9, calories: 280, protein: 7, sugar: 11, fat: 12, vitamins: 50, ingredients: { "Chia seeds (g)": 30, "Coconut milk (g)": 100, "Mango (g)": 80 } },
        { name: "Herbed Chicken Breast", fiber: 2, calories: 310, protein: 33, sugar: 0, fat: 14, vitamins: 25, ingredients: { "Chicken breast (g)": 150, "Rosemary (g)": 5, "Olive oil (g)": 10 } },
        { name: "Berry Spinach Smoothie", fiber: 5, calories: 200, protein: 8, sugar: 15, fat: 3, vitamins: 70, ingredients: { "Spinach (g)": 50, "Mixed berries (g)": 100, "Greek yogurt (g)": 100 } },
        { name: "Lemon Dill Cod", fiber: 1, calories: 230, protein: 28, sugar: 0, fat: 7, vitamins: 20, ingredients: { "Cod (g)": 150, "Lemon juice (g)": 10, "Dill (g)": 5 } },
        { name: "Avocado Tomato Toast", fiber: 6, calories: 260, protein: 7, sugar: 4, fat: 15, vitamins: 35, ingredients: { "Whole grain bread (g)": 40, "Avocado (g)": 70, "Tomato (g)": 50 } },
        { name: "Zucchini Noodle Stir Fry", fiber: 5, calories: 230, protein: 15, sugar: 5, fat: 8, vitamins: 50, ingredients: { "Zucchini (g)": 150, "Tofu (g)": 100, "Soy sauce (g)": 15 } },
        { name: "Peanut Butter Energy Bites", fiber: 6, calories: 280, protein: 9, sugar: 10, fat: 15, vitamins: 15, ingredients: { "Peanut butter (g)": 50, "Oats (g)": 40, "Honey (g)": 15 } },
        { name: "Tomato Basil Omelette", fiber: 1, calories: 270, protein: 20, sugar: 3, fat: 18, vitamins: 30, ingredients: { "Eggs (g)": 120, "Tomato (g)": 50, "Basil (g)": 10 } },
        { name: "Sweet Corn Salad", fiber: 4, calories: 230, protein: 8, sugar: 6, fat: 8, vitamins: 40, ingredients: { "Corn (g)": 100, "Black beans (g)": 80, "Red onion (g)": 30 } },
        { name: "Banana Almond Smoothie", fiber: 5, calories: 250, protein: 7, sugar: 14, fat: 9, vitamins: 20, ingredients: { "Banana (g)": 100, "Almond milk (g)": 150, "Almond butter (g)": 20 } },
        { name: "Grilled Veggie Skewers", fiber: 6, calories: 220, protein: 8, sugar: 7, fat: 6, vitamins: 55, ingredients: { "Zucchini (g)": 100, "Bell pepper (g)": 80, "Mushrooms (g)": 80 } },
        { name: "Lentil Veggie Bowl", fiber: 9, calories: 280, protein: 15, sugar: 4, fat: 7, vitamins: 60, ingredients: { "Lentils (g)": 120, "Carrots (g)": 70, "Spinach (g)": 50 } },
        { name: "Honey Glazed Carrots", fiber: 3, calories: 180, protein: 3, sugar: 12, fat: 4, vitamins: 40, ingredients: { "Carrots (g)": 150, "Honey (g)": 20, "Butter (g)": 10 } },
        { name: "Spicy Black Bean Soup", fiber: 10, calories: 260, protein: 14, sugar: 3, fat: 5, vitamins: 50, ingredients: { "Black beans (g)": 150, "Tomato (g)": 80, "Chili powder (g)": 5 } },
        { name: "Mushroom Spinach Wrap", fiber: 5, calories: 240, protein: 10, sugar: 3, fat: 7, vitamins: 45, ingredients: { "Mushrooms (g)": 100, "Spinach (g)": 80, "Whole wheat wrap (g)": 60 } },
        { name: "Cucumber Avocado Salad", fiber: 6, calories: 210, protein: 4, sugar: 3, fat: 14, vitamins: 40, ingredients: { "Cucumber (g)": 120, "Avocado (g)": 70, "Lime juice (g)": 10 } },
        { name: "Carrot Ginger Soup", fiber: 5, calories: 200, protein: 5, sugar: 7, fat: 6, vitamins: 50, ingredients: { "Carrots (g)": 150, "Ginger (g)": 10, "Vegetable broth (g)": 100 } },
        { name: "Turkey Sweet Potato Mash", fiber: 6, calories: 300, protein: 30, sugar: 4, fat: 10, vitamins: 60, ingredients: { "Ground turkey (g)": 150, "Sweet potato (g)": 150, "Onion (g)": 40 } },
        { name: "Garlic Butter Cod", fiber: 1, calories: 270, protein: 30, sugar: 0, fat: 14, vitamins: 20, ingredients: { "Cod (g)": 150, "Butter (g)": 15, "Garlic (g)": 10 } },
        { name: "Spinach Feta Omelette", fiber: 2, calories: 280, protein: 22, sugar: 2, fat: 20, vitamins: 40, ingredients: { "Eggs (g)": 120, "Spinach (g)": 50, "Feta cheese (g)": 30 } },
        { name: "Apple Cinnamon Yogurt", fiber: 3, calories: 190, protein: 10, sugar: 13, fat: 4, vitamins: 15, ingredients: { "Apple (g)": 100, "Greek yogurt (g)": 150, "Cinnamon (g)": 2 } },
        { name: "Roasted Beet Salad", fiber: 6, calories: 230, protein: 7, sugar: 7, fat: 10, vitamins: 50, ingredients: { "Beets (g)": 150, "Goat cheese (g)": 40, "Walnuts (g)": 20 } },
        { name: "BBQ Chicken Bowl", fiber: 3, calories: 310, protein: 32, sugar: 6, fat: 15, vitamins: 25, ingredients: { "Chicken breast (g)": 150, "BBQ sauce (g)": 30, "Corn (g)": 80 } },
        { name: "Cauliflower Rice Stir Fry", fiber: 5, calories: 220, protein: 12, sugar: 4, fat: 8, vitamins: 45, ingredients: { "Cauliflower rice (g)": 150, "Carrots (g)": 70, "Peas (g)": 50 } },
        { name: "Peach Almond Salad", fiber: 4, calories: 240, protein: 8, sugar: 9, fat: 12, vitamins: 30, ingredients: { "Peach (g)": 100, "Almonds (g)": 30, "Spinach (g)": 50 } },
        { name: "Buffalo Cauliflower Bites", fiber: 5, calories: 210, protein: 6, sugar: 3, fat: 10, vitamins: 40, ingredients: { "Cauliflower (g)": 150, "Buffalo sauce (g)": 30, "Olive oil (g)": 10 } },
        { name: "Strawberry Spinach Salad", fiber: 5, calories: 200, protein: 5, sugar: 10, fat: 8, vitamins: 65, ingredients: { "Strawberries (g)": 100, "Spinach (g)": 80, "Walnuts (g)": 20 } },
        { name: "Turkey Avocado Wrap", fiber: 6, calories: 300, protein: 28, sugar: 2, fat: 15, vitamins: 30, ingredients: { "Turkey breast (g)": 120, "Avocado (g)": 70, "Whole wheat wrap (g)": 60 } },
        { name: "Eggplant Tomato Bake", fiber: 6, calories: 250, protein: 8, sugar: 6, fat: 10, vitamins: 45, ingredients: { "Eggplant (g)": 150, "Tomato sauce (g)": 80, "Mozzarella (g)": 40 } },
        { name: "Coconut Chia Smoothie", fiber: 8, calories: 270, protein: 7, sugar: 12, fat: 14, vitamins: 50, ingredients: { "Chia seeds (g)": 30, "Coconut milk (g)": 120, "Banana (g)": 100 } },
        { name: "Zesty Lime Chicken", fiber: 2, calories: 310, protein: 33, sugar: 1, fat: 13, vitamins: 25, ingredients: { "Chicken breast (g)": 150, "Lime juice (g)": 10, "Chili powder (g)": 5 } },
        { name: "Veggie Hummus Wrap", fiber: 7, calories: 280, protein: 9, sugar: 5, fat: 8, vitamins: 40, ingredients: { "Hummus (g)": 50, "Cucumber (g)": 80, "Whole wheat wrap (g)": 60 } },
        { name: "Beef Broccoli Stir Fry", fiber: 4, calories: 320, protein: 30, sugar: 3, fat: 16, vitamins: 35, ingredients: { "Lean beef (g)": 150, "Broccoli (g)": 100, "Soy sauce (g)": 15 } },
        { name: "Carrot Apple Salad", fiber: 5, calories: 220, protein: 4, sugar: 10, fat: 6, vitamins: 50, ingredients: { "Carrots (g)": 100, "Apple (g)": 100, "Walnuts (g)": 20 } },
        { name: "Creamy Avocado Toast", fiber: 6, calories: 270, protein: 7, sugar: 2, fat: 16, vitamins: 35, ingredients: { "Whole grain bread (g)": 40, "Avocado (g)": 80, "Lemon juice (g)": 10 } },
        { name: "Lentil Veggie Wrap", fiber: 8, calories: 290, protein: 15, sugar: 4, fat: 8, vitamins: 50, ingredients: { "Lentils (g)": 100, "Spinach (g)": 60, "Whole wheat wrap (g)": 60 } },
        { name: "Mango Black Bean Salsa", fiber: 7, calories: 260, protein: 9, sugar: 8, fat: 6, vitamins: 55, ingredients: { "Black beans (g)": 100, "Mango (g)": 90, "Red onion (g)": 40 } },
        { name: "Garlic Herb Roasted Chicken", fiber: 2, calories: 320, protein: 35, sugar: 1, fat: 15, vitamins: 30, ingredients: { "Chicken breast (g)": 150, "Garlic (g)": 10, "Rosemary (g)": 5 } },
        { name: "Chickpea Avocado Salad", fiber: 8, calories: 280, protein: 12, sugar: 4, fat: 14, vitamins: 50, ingredients: { "Chickpeas (g)": 120, "Avocado (g)": 70, "Lemon juice (g)": 10 } },
        { name: "Berry Oat Smoothie", fiber: 6, calories: 230, protein: 7, sugar: 14, fat: 4, vitamins: 60, ingredients: { "Mixed berries (g)": 100, "Oats (g)": 50, "Almond milk (g)": 150 } },
        { name: "Quinoa Black Bean Salad", fiber: 9, calories: 310, protein: 13, sugar: 3, fat: 8, vitamins: 55, ingredients: { "Quinoa (g)": 80, "Black beans (g)": 100, "Cilantro (g)": 10 } },
        { name: "Cinnamon Apple Pancakes", fiber: 5, calories: 270, protein: 8, sugar: 12, fat: 6, vitamins: 20, ingredients: { "Apple (g)": 80, "Oats (g)": 60, "Egg (g)": 60 } },
        { name: "Baked Salmon with Dill", fiber: 1, calories: 300, protein: 32, sugar: 0, fat: 16, vitamins: 25, ingredients: { "Salmon (g)": 150, "Dill (g)": 5, "Lemon juice (g)": 10 } },
        { name: "Sweet Potato and Kale Hash", fiber: 7, calories: 280, protein: 10, sugar: 5, fat: 9, vitamins: 70, ingredients: { "Sweet potato (g)": 150, "Kale (g)": 80, "Onion (g)": 40 } },
        { name: "Turkey Spinach Wrap", fiber: 6, calories: 290, protein: 28, sugar: 2, fat: 12, vitamins: 35, ingredients: { "Turkey breast (g)": 120, "Spinach (g)": 60, "Whole wheat wrap (g)": 60 } },
        { name: "Peanut Butter Banana Toast", fiber: 5, calories: 260, protein: 7, sugar: 15, fat: 12, vitamins: 20, ingredients: { "Whole grain bread (g)": 40, "Peanut butter (g)": 20, "Banana (g)": 100 } },
        { name: "Roasted Veggie Pasta", fiber: 6, calories: 300, protein: 10, sugar: 7, fat: 8, vitamins: 50, ingredients: { "Pasta (g)": 100, "Zucchini (g)": 80, "Bell pepper (g)": 80 } },
        { name: "Greek Yogurt with Honey & Nuts", fiber: 3, calories: 210, protein: 14, sugar: 10, fat: 8, vitamins: 15, ingredients: { "Greek yogurt (g)": 150, "Honey (g)": 15, "Walnuts (g)": 20 } },
        { name: "Cauliflower Tabbouleh Salad", fiber: 6, calories: 220, protein: 7, sugar: 4, fat: 7, vitamins: 40, ingredients: { "Cauliflower (g)": 150, "Parsley (g)": 30, "Tomato (g)": 50 } },
        { name: "Spicy Tofu Lettuce Wraps", fiber: 5, calories: 240, protein: 18, sugar: 3, fat: 10, vitamins: 45, ingredients: { "Tofu (g)": 120, "Lettuce (g)": 60, "Sriracha sauce (g)": 15 } },
        { name: "Tomato Cucumber Salad", fiber: 4, calories: 180, protein: 5, sugar: 5, fat: 6, vitamins: 40, ingredients: { "Tomato (g)": 100, "Cucumber (g)": 100, "Olive oil (g)": 10 } },
        { name: "Black Bean and Corn Salsa", fiber: 7, calories: 260, protein: 9, sugar: 4, fat: 7, vitamins: 55, ingredients: { "Black beans (g)": 100, "Corn (g)": 100, "Red onion (g)": 30 } },
        { name: "Avocado Egg Breakfast Bowl", fiber: 6, calories: 300, protein: 18, sugar: 2, fat: 22, vitamins: 40, ingredients: { "Eggs (g)": 120, "Avocado (g)": 70, "Spinach (g)": 50 } },
        { name: "Pumpkin Spice Overnight Oats", fiber: 8, calories: 280, protein: 10, sugar: 12, fat: 8, vitamins: 50, ingredients: { "Oats (g)": 60, "Pumpkin puree (g)": 80, "Almond milk (g)": 150 } },
        { name: "Quinoa Veggie Stir Fry", fiber: 7, calories: 290, protein: 14, sugar: 5, fat: 7, vitamins: 55, ingredients: { "Quinoa (g)": 80, "Broccoli (g)": 100, "Carrot (g)": 70 } },
        { name: "Almond Butter Apple Slices", fiber: 5, calories: 220, protein: 6, sugar: 10, fat: 12, vitamins: 15, ingredients: { "Apple (g)": 150, "Almond butter (g)": 20 } },
        { name: "Garlic Lemon Chicken Thighs", fiber: 2, calories: 320, protein: 33, sugar: 1, fat: 16, vitamins: 30, ingredients: { "Chicken thighs (g)": 150, "Garlic (g)": 10, "Lemon juice (g)": 10 } },
        { name: "Sweet Potato Chickpea Curry", fiber: 8, calories: 290, protein: 14, sugar: 6, fat: 8, vitamins: 60, ingredients: { "Sweet potato (g)": 150, "Chickpeas (g)": 120, "Coconut milk (g)": 50 } },
        { name: "Cucumber Mint Salad", fiber: 4, calories: 180, protein: 4, sugar: 3, fat: 7, vitamins: 35, ingredients: { "Cucumber (g)": 120, "Mint (g)": 10, "Lime juice (g)": 10 } },
        { name: "Peach Cottage Cheese Bowl", fiber: 2, calories: 190, protein: 16, sugar: 9, fat: 5, vitamins: 15, ingredients: { "Cottage cheese (g)": 150, "Peach (g)": 80 } },
        { name: "Turkey Meatball Zucchini Noodles", fiber: 5, calories: 300, protein: 30, sugar: 4, fat: 12, vitamins: 40, ingredients: { "Ground turkey (g)": 150, "Zucchini (g)": 100, "Tomato sauce (g)": 80 } },
        { name: "Mango Spinach Smoothie", fiber: 5, calories: 220, protein: 6, sugar: 14, fat: 4, vitamins: 60, ingredients: { "Mango (g)": 100, "Spinach (g)": 50, "Greek yogurt (g)": 100 } },
        { name: "Roasted Cauliflower with Tahini", fiber: 6, calories: 250, protein: 8, sugar: 4, fat: 12, vitamins: 40, ingredients: { "Cauliflower (g)": 150, "Tahini (g)": 30, "Lemon juice (g)": 10 } },
        { name: "Banana Nut Oatmeal", fiber: 6, calories: 280, protein: 8, sugar: 12, fat: 10, vitamins: 20, ingredients: { "Oats (g)": 60, "Banana (g)": 100, "Walnuts (g)": 20 } },
        { name: "Spicy Lentil Soup", fiber: 9, calories: 270, protein: 15, sugar: 3, fat: 6, vitamins: 50, ingredients: { "Lentils (g)": 120, "Tomato (g)": 80, "Chili powder (g)": 5 } },
        { name: "Avocado Chickpea Toast", fiber: 7, calories: 280, protein: 10, sugar: 3, fat: 14, vitamins: 40, ingredients: { "Whole grain bread (g)": 40, "Avocado (g)": 70, "Chickpeas (g)": 100 } },
        { name: "Herb Grilled Shrimp", fiber: 1, calories: 220, protein: 25, sugar: 1, fat: 7, vitamins: 20, ingredients: { "Shrimp (g)": 120, "Rosemary (g)": 5, "Garlic (g)": 10 } },
        { name: "Tomato Basil Soup", fiber: 5, calories: 210, protein: 6, sugar: 7, fat: 6, vitamins: 45, ingredients: { "Tomato (g)": 150, "Basil (g)": 10, "Garlic (g)": 10 } },
        { name: "Peanut Butter Energy Bars", fiber: 6, calories: 280, protein: 9, sugar: 10, fat: 15, vitamins: 15, ingredients: { "Peanut butter (g)": 50, "Oats (g)": 40, "Honey (g)": 15 } },
        { name: "Grilled Veggie Skewers", fiber: 6, calories: 220, protein: 8, sugar: 7, fat: 6, vitamins: 55, ingredients: { "Zucchini (g)": 100, "Bell pepper (g)": 80, "Mushrooms (g)": 80 } },
        { name: "Eggplant Parmesan Bake", fiber: 6, calories: 270, protein: 12, sugar: 6, fat: 14, vitamins: 45, ingredients: { "Eggplant (g)": 150, "Tomato sauce (g)": 80, "Mozzarella (g)": 50 } },
        { name: "Coconut Mango Chia Pudding", fiber: 9, calories: 280, protein: 7, sugar: 11, fat: 12, vitamins: 50, ingredients: { "Chia seeds (g)": 30, "Coconut milk (g)": 100, "Mango (g)": 80 } },
        { name: "Lemon Herb Chicken Salad", fiber: 3, calories: 310, protein: 33, sugar: 1, fat: 14, vitamins: 35, ingredients: { "Chicken breast (g)": 150, "Lemon juice (g)": 10, "Parsley (g)": 5 } },
        { name: "Spinach Feta Wrap", fiber: 5, calories: 270, protein: 20, sugar: 3, fat: 16, vitamins: 40, ingredients: { "Spinach (g)": 60, "Feta cheese (g)": 40, "Whole wheat wrap (g)": 60 } },
        { name: "Carrot Ginger Smoothie", fiber: 5, calories: 200, protein: 6, sugar: 8, fat: 6, vitamins: 50, ingredients: { "Carrots (g)": 150, "Ginger (g)": 10, "Greek yogurt (g)": 100 } },
        { name: "Turkey Sweet Potato Bowl", fiber: 6, calories: 320, protein: 32, sugar: 4, fat: 11, vitamins: 60, ingredients: { "Ground turkey (g)": 150, "Sweet potato (g)": 150, "Onion (g)": 40 } },
        { name: "Egg Avocado Toast", fiber: 5, calories: 220, protein: 9, sugar: 2, fat: 14, vitamins: 18, ingredients: { "Whole Grain Bread (g)": 50, "Avocado (g)": 70, "Egg (g)": 50 } },
        { name: "Greek Yogurt with Berries", fiber: 3, calories: 160, protein: 10, sugar: 12, fat: 2, vitamins: 15, ingredients: { "Greek Yogurt (g)": 150, "Blueberries (g)": 50, "Honey (g)": 10 } },
        { name: "Chicken Rice Bowl", fiber: 1, calories: 300, protein: 25, sugar: 0, fat: 8, vitamins: 6, ingredients: { "Grilled Chicken (g)": 100, "Cooked Rice (g)": 100, "Steamed Broccoli (g)": 50 } },
        { name: "Banana Peanut Wrap", fiber: 4, calories: 250, protein: 7, sugar: 14, fat: 11, vitamins: 10, ingredients: { "Whole Wheat Tortilla (g)": 60, "Banana (g)": 100, "Peanut Butter (g)": 20 } },
        { name: "Tuna Stuffed Avocado", fiber: 6, calories: 280, protein: 18, sugar: 1, fat: 22, vitamins: 12, ingredients: { "Avocado (g)": 100, "Canned Tuna (g)": 70, "Lemon Juice (g)": 10 } },
        { name: "Apple Cheese Snack", fiber: 3, calories: 200, protein: 8, sugar: 12, fat: 11, vitamins: 10, ingredients: { "Apple (g)": 100, "Cheddar Cheese (g)": 50, "Almonds (g)": 20 } },
        { name: "Cottage Berry Bowl", fiber: 2, calories: 180, protein: 15, sugar: 8, fat: 5, vitamins: 10, ingredients: { "Cottage Cheese (g)": 120, "Raspberries (g)": 50, "Chia Seeds (g)": 10 } },
        { name: "Sweet Potato and Egg", fiber: 4, calories: 190, protein: 9, sugar: 4, fat: 7, vitamins: 14, ingredients: { "Sweet Potato (g)": 100, "Egg (g)": 50, "Olive Oil (g)": 10 } },
        { name: "Turkey Cheese Roll-Ups", fiber: 1, calories: 210, protein: 20, sugar: 1, fat: 14, vitamins: 6, ingredients: { "Turkey Slices (g)": 80, "Swiss Cheese (g)": 40, "Cucumber (g)": 50 } },
        { name: "Peanut Butter Banana Smoothie", fiber: 4, calories: 200, protein: 5, sugar: 12, fat: 10, vitamins: 15, ingredients: { "Banana (g)": 100, "Peanut Butter (g)": 50, "Greek Yogurt (g)": 50 } },
        { name: "Tuna Salad Bowl", fiber: 2, calories: 250, protein: 25, sugar: 2, fat: 12, vitamins: 10, ingredients: { "Canned Tuna (g)": 100, "Lettuce (g)": 50, "Tomato (g)": 50 } },
        { name: "Eggplant Parmesan", fiber: 3, calories: 280, protein: 15, sugar: 4, fat: 16, vitamins: 12, ingredients: { "Eggplant (g)": 150, "Tomato Sauce (g)": 80, "Mozzarella Cheese (g)": 50 } },
        { name: "Greek Yogurt Parfait", fiber: 2, calories: 170, protein: 10, sugar: 10, fat: 3, vitamins: 15, ingredients: { "Greek Yogurt (g)": 100, "Mixed Berries (g)": 50, "Honey (g)": 10 } },
        { name: "Chicken and Rice Bowl", fiber: 1, calories: 300, protein: 25, sugar: 0, fat: 8, vitamins: 6, ingredients: { "Grilled Chicken (g)": 100, "Cooked Rice (g)": 100, "Steamed Broccoli (g)": 50 } },
        { name: "Turkey Wrap", fiber: 2, calories: 250, protein: 20, sugar: 1, fat: 12, vitamins: 8, ingredients: { "Turkey Slices (g)": 80, "Whole Wheat Wrap (g)": 60, "Lettuce (g)": 50 } },
        { name: "Mediterranean Falafel Bowl", fiber: 9, calories: 310, protein: 12, sugar: 4, fat: 14, vitamins: 45, ingredients: { "Falafel (g)": 120, "Cucumber (g)": 80, "Tahini (g)": 20 } },
        { name: "Teriyaki Salmon Rice Bowl", fiber: 4, calories: 340, protein: 28, sugar: 8, fat: 12, vitamins: 35, ingredients: { "Salmon (g)": 130, "Brown rice (g)": 100, "Teriyaki sauce (g)": 20 } },
        { name: "Mushroom Spinach Frittata", fiber: 3, calories: 260, protein: 18, sugar: 2, fat: 16, vitamins: 30, ingredients: { "Eggs (g)": 120, "Mushrooms (g)": 80, "Spinach (g)": 60 } },
        { name: "Blueberry Almond Smoothie", fiber: 6, calories: 240, protein: 8, sugar: 14, fat: 9, vitamins: 25, ingredients: { "Blueberries (g)": 100, "Almond milk (g)": 200, "Almonds (g)": 20 } },
        { name: "Buffalo Cauliflower Bites", fiber: 5, calories: 220, protein: 6, sugar: 3, fat: 10, vitamins: 30, ingredients: { "Cauliflower (g)": 150, "Hot sauce (g)": 15, "Breadcrumbs (g)": 30 } },
        { name: "Tuna Avocado Wrap", fiber: 6, calories: 290, protein: 24, sugar: 2, fat: 14, vitamins: 25, ingredients: { "Tuna (g)": 100, "Avocado (g)": 70, "Whole wheat wrap (g)": 60 } },
        { name: "Coconut Chia Pudding", fiber: 10, calories: 250, protein: 7, sugar: 8, fat: 16, vitamins: 15, ingredients: { "Chia seeds (g)": 30, "Coconut milk (g)": 150, "Honey (g)": 10 } },
        { name: "Edamame Quinoa Bowl", fiber: 8, calories: 300, protein: 15, sugar: 3, fat: 9, vitamins: 40, ingredients: { "Edamame (g)": 100, "Quinoa (g)": 80, "Sesame oil (g)": 10 } },
        { name: "Caprese Stuffed Chicken", fiber: 2, calories: 330, protein: 35, sugar: 3, fat: 14, vitamins: 25, ingredients: { "Chicken breast (g)": 150, "Mozzarella (g)": 30, "Tomato (g)": 50 } },
        { name: "Kale Caesar Salad", fiber: 5, calories: 240, protein: 10, sugar: 2, fat: 16, vitamins: 60, ingredients: { "Kale (g)": 100, "Parmesan (g)": 20, "Caesar dressing (g)": 30 } },
        { name: "Pineapple Coconut Smoothie", fiber: 4, calories: 230, protein: 5, sugar: 18, fat: 8, vitamins: 35, ingredients: { "Pineapple (g)": 120, "Coconut milk (g)": 150, "Banana (g)": 50 } },
        { name: "Lemon Garlic Shrimp Pasta", fiber: 3, calories: 320, protein: 22, sugar: 3, fat: 10, vitamins: 20, ingredients: { "Shrimp (g)": 120, "Pasta (g)": 100, "Lemon (g)": 20 } },
        { name: "Stuffed Bell Peppers", fiber: 6, calories: 280, protein: 18, sugar: 6, fat: 8, vitamins: 55, ingredients: { "Bell peppers (g)": 150, "Ground turkey (g)": 100, "Brown rice (g)": 50 } },
        { name: "Raspberry Chia Jam Toast", fiber: 7, calories: 240, protein: 6, sugar: 9, fat: 8, vitamins: 30, ingredients: { "Whole grain bread (g)": 40, "Raspberries (g)": 80, "Chia seeds (g)": 15 } },
        { name: "Sesame Ginger Tofu Stir Fry", fiber: 6, calories: 270, protein: 16, sugar: 5, fat: 12, vitamins: 45, ingredients: { "Tofu (g)": 120, "Broccoli (g)": 80, "Sesame oil (g)": 10 } },
        { name: "Watermelon Feta Salad", fiber: 2, calories: 190, protein: 7, sugar: 12, fat: 9, vitamins: 25, ingredients: { "Watermelon (g)": 150, "Feta cheese (g)": 30, "Mint (g)": 5 } },
        { name: "Turmeric Ginger Lentil Soup", fiber: 8, calories: 260, protein: 14, sugar: 3, fat: 5, vitamins: 40, ingredients: { "Lentils (g)": 120, "Turmeric (g)": 5, "Ginger (g)": 10 } },
        { name: "Pistachio Crusted Salmon", fiber: 3, calories: 310, protein: 30, sugar: 1, fat: 18, vitamins: 30, ingredients: { "Salmon (g)": 140, "Pistachios (g)": 30, "Lemon juice (g)": 10 } },
        { name: "Butternut Squash Soup", fiber: 6, calories: 220, protein: 5, sugar: 8, fat: 7, vitamins: 65, ingredients: { "Butternut squash (g)": 200, "Coconut milk (g)": 50, "Nutmeg (g)": 2 } },
        { name: "Tempeh BLT Sandwich", fiber: 7, calories: 310, protein: 16, sugar: 4, fat: 14, vitamins: 35, ingredients: { "Tempeh (g)": 100, "Whole grain bread (g)": 80, "Tomato (g)": 50 } },
        { name: "Dragon Fruit Smoothie Bowl", fiber: 7, calories: 250, protein: 6, sugar: 16, fat: 5, vitamins: 40, ingredients: { "Dragon fruit (g)": 150, "Banana (g)": 50, "Almond milk (g)": 100 } },
        { name: "Eggplant Parmesan", fiber: 6, calories: 290, protein: 12, sugar: 7, fat: 16, vitamins: 30, ingredients: { "Eggplant (g)": 150, "Mozzarella (g)": 40, "Tomato sauce (g)": 80 } },
        { name: "Pomegranate Walnut Salad", fiber: 5, calories: 230, protein: 5, sugar: 10, fat: 14, vitamins: 35, ingredients: { "Mixed greens (g)": 100, "Pomegranate seeds (g)": 50, "Walnuts (g)": 30 } },
        { name: "Ginger Carrot Soup", fiber: 5, calories: 180, protein: 4, sugar: 9, fat: 5, vitamins: 70, ingredients: { "Carrots (g)": 200, "Ginger (g)": 10, "Coconut milk (g)": 50 } },
        { name: "Sardine Avocado Toast", fiber: 6, calories: 280, protein: 18, sugar: 2, fat: 16, vitamins: 40, ingredients: { "Whole grain bread (g)": 40, "Sardines (g)": 80, "Avocado (g)": 60 } },
        { name: "Kimchi Fried Rice", fiber: 4, calories: 310, protein: 10, sugar: 3, fat: 8, vitamins: 35, ingredients: { "Brown rice (g)": 120, "Kimchi (g)": 80, "Egg (g)": 50 } },
        { name: "Chocolate Cherry Smoothie", fiber: 6, calories: 240, protein: 8, sugar: 15, fat: 7, vitamins: 25, ingredients: { "Cherries (g)": 100, "Cacao powder (g)": 10, "Almond milk (g)": 200 } },
        { name: "Zucchini Noodles with Pesto", fiber: 4, calories: 220, protein: 7, sugar: 4, fat: 16, vitamins: 30, ingredients: { "Zucchini (g)": 200, "Basil pesto (g)": 40, "Pine nuts (g)": 10 } },
        { name: "Beet Goat Cheese Salad", fiber: 5, calories: 230, protein: 8, sugar: 9, fat: 12, vitamins: 45, ingredients: { "Beets (g)": 120, "Goat cheese (g)": 30, "Arugula (g)": 80 } },
        { name: "Butter Chicken Curry", fiber: 3, calories: 350, protein: 28, sugar: 5, fat: 18, vitamins: 25, ingredients: { "Chicken (g)": 150, "Tomato sauce (g)": 100, "Butter (g)": 20, "Garam masala (g)": 5 } },
        { name: "Chana Masala", fiber: 9, calories: 280, protein: 12, sugar: 6, fat: 8, vitamins: 45, ingredients: { "Chickpeas (g)": 150, "Tomatoes (g)": 100, "Onion (g)": 50, "Cumin (g)": 5 } },
        { name: "Palak Paneer", fiber: 5, calories: 300, protein: 15, sugar: 4, fat: 16, vitamins: 60, ingredients: { "Spinach (g)": 150, "Paneer cheese (g)": 100, "Onion (g)": 50, "Garam masala (g)": 5 } },
        { name: "Vegetable Biryani", fiber: 7, calories: 320, protein: 10, sugar: 5, fat: 9, vitamins: 40, ingredients: { "Basmati rice (g)": 100, "Mixed vegetables (g)": 150, "Biryani spices (g)": 10 } },
        { name: "Miso Soup with Tofu", fiber: 3, calories: 180, protein: 12, sugar: 2, fat: 6, vitamins: 30, ingredients: { "Tofu (g)": 100, "Miso paste (g)": 20, "Seaweed (g)": 10, "Green onion (g)": 20 } },
        { name: "Teriyaki Salmon Bowl", fiber: 4, calories: 340, protein: 30, sugar: 8, fat: 14, vitamins: 35, ingredients: { "Salmon (g)": 150, "Brown rice (g)": 100, "Teriyaki sauce (g)": 30 } },
        { name: "Vegetable Tempura", fiber: 5, calories: 280, protein: 8, sugar: 6, fat: 15, vitamins: 25, ingredients: { "Mixed vegetables (g)": 200, "Tempura batter (g)": 50, "Dipping sauce (g)": 20 } },
        { name: "Soba Noodle Salad", fiber: 6, calories: 260, protein: 12, sugar: 4, fat: 7, vitamins: 30, ingredients: { "Soba noodles (g)": 100, "Cucumber (g)": 80, "Sesame oil (g)": 10 } },
        { name: "Greek Salad", fiber: 5, calories: 240, protein: 8, sugar: 5, fat: 16, vitamins: 45, ingredients: { "Cucumber (g)": 100, "Tomato (g)": 100, "Feta cheese (g)": 50, "Olives (g)": 30 } },
        { name: "Tabbouleh", fiber: 7, calories: 220, protein: 6, sugar: 3, fat: 10, vitamins: 40, ingredients: { "Bulgur wheat (g)": 80, "Parsley (g)": 50, "Tomato (g)": 80, "Olive oil (g)": 15 } },
        { name: "Baked Falafel Bowl", fiber: 8, calories: 310, protein: 14, sugar: 4, fat: 12, vitamins: 50, ingredients: { "Chickpeas (g)": 150, "Herbs (g)": 20, "Tahini (g)": 30 } },
        { name: "Grilled Halloumi Salad", fiber: 4, calories: 290, protein: 16, sugar: 3, fat: 18, vitamins: 35, ingredients: { "Halloumi cheese (g)": 100, "Mixed greens (g)": 100, "Olive oil (g)": 15 } },
        { name: "Miso Glazed Cod", fiber: 1, calories: 260, protein: 32, sugar: 5, fat: 8, vitamins: 20, ingredients: { "Cod (g)": 150, "Miso paste (g)": 20, "Honey (g)": 10 } },
        { name: "Roasted Brussels Sprouts Hash", fiber: 8, calories: 240, protein: 9, sugar: 5, fat: 10, vitamins: 65, ingredients: { "Brussels sprouts (g)": 150, "Sweet potato (g)": 100, "Onion (g)": 40 } },
        { name: "Fig Ricotta Toast", fiber: 4, calories: 250, protein: 10, sugar: 14, fat: 9, vitamins: 15, ingredients: { "Whole grain bread (g)": 40, "Ricotta cheese (g)": 50, "Figs (g)": 60 } },
        { name: "Cajun Shrimp Lettuce Wraps", fiber: 3, calories: 210, protein: 24, sugar: 2, fat: 8, vitamins: 25, ingredients: { "Shrimp (g)": 120, "Lettuce (g)": 80, "Cajun seasoning (g)": 5 } },
        { name: "Matcha Green Tea Smoothie", fiber: 5, calories: 220, protein: 7, sugar: 10, fat: 7, vitamins: 30, ingredients: { "Banana (g)": 100, "Matcha powder (g)": 5, "Almond milk (g)": 200 } },
        { name: "Roasted Red Pepper Hummus", fiber: 6, calories: 240, protein: 8, sugar: 3, fat: 14, vitamins: 30, ingredients: { "Chickpeas (g)": 120, "Red pepper (g)": 50, "Tahini (g)": 20 } },
        { name: "Blackberry Mint Salad", fiber: 6, calories: 190, protein: 4, sugar: 8, fat: 8, vitamins: 40, ingredients: { "Mixed greens (g)": 100, "Blackberries (g)": 80, "Mint (g)": 10 } },
        { name: "Turmeric Golden Milk", fiber: 2, calories: 160, protein: 5, sugar: 6, fat: 9, vitamins: 15, ingredients: { "Almond milk (g)": 250, "Turmeric (g)": 5, "Honey (g)": 10 } },
        { name: "Artichoke Spinach Frittata", fiber: 5, calories: 270, protein: 16, sugar: 2, fat: 18, vitamins: 35, ingredients: { "Eggs (g)": 120, "Artichoke hearts (g)": 80, "Spinach (g)": 60 } },
        { name: "Jicama Citrus Salad", fiber: 7, calories: 170, protein: 3, sugar: 10, fat: 5, vitamins: 45, ingredients: { "Jicama (g)": 120, "Orange (g)": 100, "Lime juice (g)": 15 } },
        { name: "Harissa Roasted Vegetables", fiber: 7, calories: 210, protein: 5, sugar: 8, fat: 9, vitamins: 60, ingredients: { "Cauliflower (g)": 100, "Carrot (g)": 100, "Harissa paste (g)": 15 } },
        { name: "Smoked Salmon Cucumber Bites", fiber: 1, calories: 180, protein: 15, sugar: 1, fat: 10, vitamins: 15, ingredients: { "Smoked salmon (g)": 80, "Cucumber (g)": 100, "Cream cheese (g)": 30 } },
        { name: "Grapefruit Avocado Salad", fiber: 6, calories: 220, protein: 4, sugar: 8, fat: 15, vitamins: 50, ingredients: { "Grapefruit (g)": 120, "Avocado (g)": 70, "Arugula (g)": 50 } },
        { name: "Lentil Mushroom Burgers", fiber: 8, calories: 280, protein: 14, sugar: 3, fat: 9, vitamins: 30, ingredients: { "Lentils (g)": 100, "Mushrooms (g)": 80, "Oats (g)": 30 } },
        { name: "Papaya Lime Smoothie", fiber: 5, calories: 200, protein: 4, sugar: 16, fat: 3, vitamins: 65, ingredients: { "Papaya (g)": 150, "Lime juice (g)": 15, "Coconut water (g)": 150 } },
        { name: "Spaghetti Squash Primavera", fiber: 6, calories: 220, protein: 7, sugar: 6, fat: 8, vitamins: 55, ingredients: { "Spaghetti squash (g)": 150, "Bell peppers (g)": 80, "Zucchini (g)": 80 } },
        { name: "Cranberry Walnut Chicken Salad", fiber: 4, calories: 290, protein: 25, sugar: 7, fat: 14, vitamins: 25, ingredients: { "Chicken breast (g)": 120, "Cranberries (g)": 30, "Walnuts (g)": 20 } },
        { name: "Vanilla Chai Overnight Oats", fiber: 7, calories: 270, protein: 9, sugar: 11, fat: 7, vitamins: 20, ingredients: { "Oats (g)": 60, "Chai tea (g)": 100, "Vanilla extract (g)": 5 } },
        { name: "Roasted Garlic White Bean Dip", fiber: 6, calories: 190, protein: 9, sugar: 1, fat: 8, vitamins: 15, ingredients: { "White beans (g)": 120, "Garlic (g)": 15, "Olive oil (g)": 15 } },
        { name: "Persimmon Arugula Salad", fiber: 5, calories: 210, protein: 5, sugar: 12, fat: 10, vitamins: 40, ingredients: { "Persimmon (g)": 100, "Arugula (g)": 80, "Goat cheese (g)": 20 } },
        { name: "Cilantro Lime Shrimp Tacos", fiber: 4, calories: 280, protein: 22, sugar: 3, fat: 12, vitamins: 20, ingredients: { "Shrimp (g)": 150, "Corn Tortillas (g)": 50, "Cilantro (g)": 10 } },
        { name: "Acai Berry Bowl", fiber: 8, calories: 290, protein: 6, sugar: 14, fat: 10, vitamins: 55, ingredients: { "Acai puree (g)": 100, "Granola (g)": 40, "Mixed berries (g)": 80 } },
        { name: "Cauliflower Tikka Masala", fiber: 6, calories: 260, protein: 8, sugar: 7, fat: 12, vitamins: 40, ingredients: { "Cauliflower (g)": 150, "Tomato sauce (g)": 80, "Coconut milk (g)": 50 } },
        { name: "Halloumi Vegetable Skewers", fiber: 4, calories: 280, protein: 14, sugar: 5, fat: 18, vitamins: 35, ingredients: { "Halloumi cheese (g)": 80, "Bell peppers (g)": 80, "Zucchini (g)": 80 } },
        { name: "Mango Black Bean Quesadilla", fiber: 7, calories: 320, protein: 12, sugar: 8, fat: 10, vitamins: 30, ingredients: { "Whole wheat tortilla (g)": 60, "Black beans (g)": 80, "Mango (g)": 60 } },
        { name: "Seaweed Salmon Rice Bowl", fiber: 3, calories: 340, protein: 28, sugar: 2, fat: 14, vitamins: 40, ingredients: { "Salmon (g)": 120, "Brown rice (g)": 100, "Seaweed (g)": 10 } },
        { name: "Pumpkin Sage Risotto", fiber: 5, calories: 310, protein: 8, sugar: 4, fat: 9, vitamins: 45, ingredients: { "Arborio rice (g)": 100, "Pumpkin puree (g)": 80, "Sage (g)": 5 } },
        { name: "Cucumber Mint Gazpacho", fiber: 3, calories: 140, protein: 3, sugar: 6, fat: 4, vitamins: 30, ingredients: { "Cucumber (g)": 150, "Mint (g)": 10, "Greek yogurt (g)": 50 } },
        { name: "Jackfruit Pulled 'Pork' Sandwich", fiber: 6, calories: 280, protein: 5, sugar: 10, fat: 6, vitamins: 25, ingredients: { "Jackfruit (g)": 150, "Whole grain bun (g)": 60, "BBQ sauce (g)": 30 } },
        { name: "Fennel Orange Salad", fiber: 5, calories: 180, protein: 3, sugar: 12, fat: 8, vitamins: 45, ingredients: { "Fennel (g)": 100, "Orange (g)": 120, "Olive oil (g)": 10 } },
        { name: "Miso Eggplant", fiber: 5, calories: 210, protein: 5, sugar: 8, fat: 12, vitamins: 35, ingredients: { "Eggplant (g)": 150, "Miso paste (g)": 20, "Sesame oil (g)": 10 } },
        { name: "Kiwi Spinach Smoothie", fiber: 6, calories: 190, protein: 5, sugar: 14, fat: 3, vitamins: 60, ingredients: { "Kiwi (g)": 100, "Spinach (g)": 50, "Banana (g)": 80 } },
        { name: "Walnut Crusted Trout", fiber: 2, calories: 320, protein: 28, sugar: 1, fat: 18, vitamins: 25, ingredients: { "Trout fillet (g)": 150, "Walnuts (g)": 30, "Lemon (g)": 20 } },
        { name: "Roasted Carrot Hummus", fiber: 7, calories: 230, protein: 7, sugar: 5, fat: 12, vitamins: 50, ingredients: { "Chickpeas (g)": 100, "Carrots (g)": 100, "Tahini (g)": 20 } },
        { name: "Buckwheat Pancakes", fiber: 6, calories: 280, protein: 10, sugar: 6, fat: 8, vitamins: 20, ingredients: { "Buckwheat flour (g)": 80, "Banana (g)": 60, "Maple syrup (g)": 15 } },
        { name: "Kohlrabi Apple Slaw", fiber: 5, calories: 160, protein: 3, sugar: 10, fat: 7, vitamins: 40, ingredients: { "Kohlrabi (g)": 100, "Apple (g)": 80, "Greek yogurt (g)": 40 } },
        { name: "Sumac Roasted Cauliflower", fiber: 5, calories: 190, protein: 5, sugar: 4, fat: 10, vitamins: 35, ingredients: { "Cauliflower (g)": 200, "Sumac (g)": 5, "Olive oil (g)": 15 } },
        { name: "Sardine Niçoise Salad", fiber: 4, calories: 290, protein: 22, sugar: 3, fat: 16, vitamins: 45, ingredients: { "Sardines (g)": 100, "Green beans (g)": 80, "Olives (g)": 20 } },
        { name: "Cardamom Pear Oatmeal", fiber: 6, calories: 240, protein: 7, sugar: 12, fat: 5, vitamins: 20, ingredients: { "Oats (g)": 60, "Pear (g)": 100, "Cardamom (g)": 2 } },
        { name: "Radicchio Gorgonzola Salad", fiber: 3, calories: 220, protein: 8, sugar: 4, fat: 16, vitamins: 30, ingredients: { "Radicchio (g)": 100, "Gorgonzola cheese (g)": 30, "Walnuts (g)": 20 } },
        { name: "Tarragon Chicken Salad", fiber: 2, calories: 290, protein: 28, sugar: 2, fat: 15, vitamins: 20, ingredients: { "Chicken breast (g)": 120, "Tarragon (g)": 5, "Greek yogurt (g)": 40 } },
        { name: "Passion Fruit Chia Pudding", fiber: 9, calories: 240, protein: 7, sugar: 12, fat: 12, vitamins: 30, ingredients: { "Chia seeds (g)": 30, "Passion fruit (g)": 80, "Coconut milk (g)": 150 } },
        { name: "Roasted Delicata Squash", fiber: 6, calories: 180, protein: 3, sugar: 6, fat: 7, vitamins: 55, ingredients: { "Delicata squash (g)": 200, "Maple syrup (g)": 10, "Olive oil (g)": 10 } },
        { name: "Mackerel Pate on Rye", fiber: 5, calories: 270, protein: 18, sugar: 2, fat: 16, vitamins: 35, ingredients: { "Mackerel (g)": 80, "Rye bread (g)": 50, "Lemon juice (g)": 10 } },
        { name: "Rhubarb Compote with Yogurt", fiber: 4, calories: 190, protein: 8, sugar: 14, fat: 3, vitamins: 25, ingredients: { "Rhubarb (g)": 100, "Greek yogurt (g)": 100, "Honey (g)": 15 } },
        { name: "Dandelion Green Salad", fiber: 5, calories: 170, protein: 4, sugar: 3, fat: 10, vitamins: 70, ingredients: { "Dandelion greens (g)": 100, "Radishes (g)": 50, "Olive oil (g)": 15 } },
        { name: "Soba Noodle Veggie Bowl", fiber: 6, calories: 290, protein: 12, sugar: 5, fat: 7, vitamins: 40, ingredients: { "Soba noodles (g)": 100, "Bok choy (g)": 80, "Shiitake mushrooms (g)": 50 } },
        { name: "Guava Cottage Cheese Bowl", fiber: 5, calories: 210, protein: 16, sugar: 15, fat: 5, vitamins: 60, ingredients: { "Guava (g)": 100, "Cottage cheese (g)": 150, "Almonds (g)": 15 } },
        { name: "Za'atar Roasted Chickpeas", fiber: 8, calories: 240, protein: 10, sugar: 2, fat: 10, vitamins: 25, ingredients: { "Chickpeas (g)": 150, "Za'atar spice (g)": 5, "Olive oil (g)": 10 } },
        { name: "Endive Blue Cheese Boats", fiber: 3, calories: 180, protein: 7, sugar: 2, fat: 14, vitamins: 20, ingredients: { "Endive (g)": 100, "Blue cheese (g)": 30, "Walnuts (g)": 20 } },
        { name: "Kumquat Quinoa Salad", fiber: 6, calories: 250, protein: 8, sugar: 9, fat: 7, vitamins: 45, ingredients: { "Quinoa (g)": 80, "Kumquats (g)": 60, "Parsley (g)": 20 } },
        { name: "Celeriac Apple Soup", fiber: 5, calories: 170, protein: 4, sugar: 8, fat: 6, vitamins: 35, ingredients: { "Celeriac (g)": 150, "Apple (g)": 80, "Vegetable broth (g)": 200 } },
        { name: "Nori Wrapped Salmon", fiber: 2, calories: 280, protein: 30, sugar: 1, fat: 14, vitamins: 30, ingredients: { "Salmon (g)": 150, "Nori sheets (g)": 10, "Avocado (g)": 50 } },
        { name: "Persimmon Pecan Oatmeal", fiber: 7, calories: 270, protein: 7, sugar: 14, fat: 10, vitamins: 35, ingredients: { "Oats (g)": 60, "Persimmon (g)": 100, "Pecans (g)": 20 } },
        { name: "Romanesco Cauliflower Salad", fiber: 6, calories: 190, protein: 6, sugar: 4, fat: 9, vitamins: 60, ingredients: { "Romanesco (g)": 150, "Capers (g)": 10, "Olive oil (g)": 15 } },
        { name: "Goat Cheese Stuffed Dates", fiber: 4, calories: 220, protein: 6, sugar: 30, fat: 8, vitamins: 15, ingredients: { "Dates (g)": 80, "Goat cheese (g)": 40, "Pistachios (g)": 15 } },
        { name: "Watercress Soup", fiber: 3, calories: 160, protein: 5, sugar: 4, fat: 7, vitamins: 80, ingredients: { "Watercress (g)": 100, "Potato (g)": 80, "Vegetable broth (g)": 200 } },
        { name: "Teff Porridge with Berries", fiber: 7, calories: 250, protein: 9, sugar: 8, fat: 4, vitamins: 25, ingredients: { "Teff (g)": 60, "Mixed berries (g)": 80, "Almond milk (g)": 150 } },
        { name: "Grilled Radicchio Salad", fiber: 4, calories: 180, protein: 5, sugar: 3, fat: 12, vitamins: 40, ingredients: { "Radicchio (g)": 120, "Balsamic vinegar (g)": 15, "Parmesan (g)": 20 } },
        { name: "Plantain Black Bean Bowl", fiber: 8, calories: 310, protein: 12, sugar: 12, fat: 6, vitamins: 45, ingredients: { "Plantain (g)": 120, "Black beans (g)": 100, "Cilantro (g)": 10 } },
        { name: "Lavender Honey Yogurt", fiber: 1, calories: 170, protein: 10, sugar: 14, fat: 5, vitamins: 15, ingredients: { "Greek yogurt (g)": 150, "Honey (g)": 15, "Lavender (g)": 1 } },
        { name: "Kohlrabi Carrot Slaw", fiber: 6, calories: 150, protein: 3, sugar: 8, fat: 6, vitamins: 50, ingredients: { "Kohlrabi (g)": 100, "Carrots (g)": 80, "Apple cider vinegar (g)": 10 } },
        { name: "Trout Almond Amandine", fiber: 3, calories: 310, protein: 28, sugar: 1, fat: 18, vitamins: 25, ingredients: { "Trout fillet (g)": 150, "Almonds (g)": 30, "Lemon (g)": 20 } },
        { name: "Cardamom Plum Compote", fiber: 4, calories: 160, protein: 2, sugar: 20, fat: 1, vitamins: 30, ingredients: { "Plums (g)": 150, "Cardamom (g)": 2, "Honey (g)": 15 } },
        { name: "Farro Mushroom Risotto", fiber: 7, calories: 290, protein: 10, sugar: 3, fat: 8, vitamins: 25, ingredients: { "Farro (g)": 80, "Mushrooms (g)": 100, "Parmesan (g)": 20 } },
        { name: "Pomelo Avocado Salad", fiber: 7, calories: 230, protein: 4, sugar: 8, fat: 16, vitamins: 45, ingredients: { "Pomelo (g)": 150, "Avocado (g)": 70, "Mint (g)": 5 } },
        { name: "Nettle Soup", fiber: 4, calories: 150, protein: 6, sugar: 3, fat: 5, vitamins: 90, ingredients: { "Nettle leaves (g)": 80, "Potato (g)": 100, "Vegetable broth (g)": 200 } },
        { name: "Black Rice Pudding", fiber: 5, calories: 260, protein: 6, sugar: 12, fat: 7, vitamins: 20, ingredients: { "Black rice (g)": 60, "Coconut milk (g)": 150, "Mango (g)": 80 } },
        { name: "Purslane Tomato Salad", fiber: 4, calories: 140, protein: 3, sugar: 5, fat: 8, vitamins: 65, ingredients: { "Purslane (g)": 80, "Tomatoes (g)": 120, "Olive oil (g)": 15 } },
        { name: "Barley Mushroom Bowl", fiber: 8, calories: 270, protein: 9, sugar: 4, fat: 10, vitamins: 40, ingredients: { "Barley (g)": 100, "Mushrooms (g)": 80, "Carrots (g)": 50 } },
        { name: "Mushroom and Spinach Risotto", fiber: 6, calories: 300, protein: 15, sugar: 5, fat: 12, vitamins: 35, ingredients: { "Risotto rice (g)": 100, "Mushrooms (g)": 80, "Spinach (g)": 50 } },
        { name: "Pineapple Coconut Bowl", fiber: 5, calories: 250, protein: 4, sugar: 18, fat: 10, vitamins: 50, ingredients: { "Pineapple (g)": 150, "Coconut flakes (g)": 30, "Greek yogurt (g)": 50 } },
        { name: "Lemon Dill Salmon", fiber: 1, calories: 260, protein: 30, sugar: 2, fat: 12, vitamins: 20, ingredients: { "Salmon (g)": 150, "Lemon (g)": 20, "Dill (g)": 5 } },
        { name: "Aloo Gobi", fiber: 6, calories: 240, protein: 7, sugar: 4, fat: 9, vitamins: 40, ingredients: { "Potato (g)": 120, "Cauliflower (g)": 150, "Turmeric (g)": 5, "Cumin (g)": 3 } },
        { name: "Samosa Chaat", fiber: 7, calories: 320, protein: 9, sugar: 6, fat: 14, vitamins: 25, ingredients: { "Samosa (g)": 100, "Chickpeas (g)": 80, "Yogurt (g)": 50, "Chutney (g)": 30 } },
        { name: "Dal Makhani", fiber: 8, calories: 290, protein: 14, sugar: 3, fat: 12, vitamins: 30, ingredients: { "Black lentils (g)": 120, "Kidney beans (g)": 50, "Cream (g)": 30, "Spices (g)": 10 } },
        { name: "Tandoori Chicken", fiber: 2, calories: 310, protein: 32, sugar: 2, fat: 15, vitamins: 20, ingredients: { "Chicken (g)": 180, "Yogurt (g)": 50, "Tandoori masala (g)": 15 } },
        { name: "Okonomiyaki", fiber: 4, calories: 330, protein: 14, sugar: 5, fat: 16, vitamins: 35, ingredients: { "Cabbage (g)": 150, "Flour (g)": 80, "Egg (g)": 50, "Bonito flakes (g)": 5 } },
        { name: "Onigiri", fiber: 2, calories: 220, protein: 6, sugar: 1, fat: 3, vitamins: 15, ingredients: { "Rice (g)": 150, "Nori (g)": 5, "Umeboshi (g)": 15 } },
        { name: "Katsu Curry", fiber: 5, calories: 420, protein: 25, sugar: 8, fat: 18, vitamins: 30, ingredients: { "Chicken/Pork (g)": 120, "Panko breadcrumbs (g)": 50, "Curry sauce (g)": 100, "Rice (g)": 100 } },
        { name: "Chirashi Bowl", fiber: 3, calories: 380, protein: 28, sugar: 4, fat: 12, vitamins: 45, ingredients: { "Sushi rice (g)": 120, "Assorted sashimi (g)": 100, "Avocado (g)": 50, "Seaweed (g)": 5 } },
        { name: "Shakshuka", fiber: 5, calories: 280, protein: 14, sugar: 7, fat: 16, vitamins: 55, ingredients: { "Tomatoes (g)": 150, "Eggs (g)": 100, "Bell peppers (g)": 80, "Feta (g)": 30 } },
        { name: "Spanakopita", fiber: 4, calories: 310, protein: 10, sugar: 3, fat: 18, vitamins: 40, ingredients: { "Spinach (g)": 150, "Feta cheese (g)": 80, "Phyllo dough (g)": 60, "Olive oil (g)": 15 } },
        { name: "Moussaka", fiber: 6, calories: 360, protein: 18, sugar: 8, fat: 22, vitamins: 35, ingredients: { "Eggplant (g)": 150, "Ground lamb (g)": 100, "Tomato sauce (g)": 80, "Béchamel (g)": 50 } },
        { name: "Mezze Platter", fiber: 7, calories: 420, protein: 12, sugar: 5, fat: 25, vitamins: 45, ingredients: { "Hummus (g)": 80, "Baba ganoush (g)": 80, "Olives (g)": 40, "Pita bread (g)": 80 } },
        { name: "Rogan Josh", fiber: 3, calories: 340, protein: 26, sugar: 4, fat: 20, vitamins: 25, ingredients: { "Lamb (g)": 150, "Yogurt (g)": 50, "Kashmiri chili (g)": 5, "Spices (g)": 10 } },
        { name: "Malai Kofta", fiber: 5, calories: 320, protein: 10, sugar: 6, fat: 18, vitamins: 30, ingredients: { "Potato (g)": 100, "Paneer (g)": 80, "Cream (g)": 40, "Cashews (g)": 20 } },
        { name: "Baingan Bharta", fiber: 7, calories: 220, protein: 6, sugar: 8, fat: 12, vitamins: 45, ingredients: { "Eggplant (g)": 200, "Tomato (g)": 80, "Onion (g)": 50, "Spices (g)": 5 } },
        { name: "Dhokla", fiber: 4, calories: 180, protein: 8, sugar: 2, fat: 5, vitamins: 20, ingredients: { "Chickpea flour (g)": 100, "Yogurt (g)": 50, "Mustard seeds (g)": 5, "Green chili (g)": 10 } },
        { name: "Pav Bhaji", fiber: 6, calories: 290, protein: 9, sugar: 7, fat: 14, vitamins: 35, ingredients: { "Mixed vegetables (g)": 150, "Butter (g)": 20, "Pav bread (g)": 80, "Spices (g)": 10 } },
        { name: "Tonkatsu", fiber: 2, calories: 380, protein: 28, sugar: 2, fat: 22, vitamins: 15, ingredients: { "Pork cutlet (g)": 150, "Panko breadcrumbs (g)": 50, "Cabbage (g)": 80, "Tonkatsu sauce (g)": 20 } },
        { name: "Oyakodon", fiber: 2, calories: 320, protein: 24, sugar: 5, fat: 10, vitamins: 25, ingredients: { "Chicken (g)": 120, "Egg (g)": 100, "Rice (g)": 150, "Dashi (g)": 50 } },
        { name: "Udon Noodle Soup", fiber: 3, calories: 280, protein: 12, sugar: 4, fat: 6, vitamins: 20, ingredients: { "Udon noodles (g)": 150, "Dashi (g)": 200, "Green onion (g)": 20, "Tempura (g)": 30 } },
        { name: "Tamagoyaki", fiber: 1, calories: 220, protein: 14, sugar: 3, fat: 16, vitamins: 15, ingredients: { "Eggs (g)": 150, "Dashi (g)": 30, "Sugar (g)": 5, "Soy sauce (g)": 10 } },
        { name: "Yakitori", fiber: 1, calories: 250, protein: 22, sugar: 6, fat: 14, vitamins: 10, ingredients: { "Chicken (g)": 120, "Green onion (g)": 30, "Yakitori sauce (g)": 25 } },
        { name: "Dolmas", fiber: 5, calories: 240, protein: 6, sugar: 3, fat: 10, vitamins: 25, ingredients: { "Grape leaves (g)": 50, "Rice (g)": 80, "Pine nuts (g)": 15, "Herbs (g)": 10 } },
        { name: "Pastitsio", fiber: 4, calories: 380, protein: 18, sugar: 6, fat: 16, vitamins: 20, ingredients: { "Pasta (g)": 120, "Ground beef (g)": 100, "Béchamel sauce (g)": 80, "Tomato sauce (g)": 50 } },
        { name: "Souvlaki", fiber: 2, calories: 310, protein: 26, sugar: 3, fat: 18, vitamins: 15, ingredients: { "Pork/Chicken (g)": 150, "Olive oil (g)": 15, "Lemon (g)": 20, "Pita bread (g)": 60 } },
        { name: "Avgolemono Soup", fiber: 2, calories: 220, protein: 14, sugar: 2, fat: 8, vitamins: 20, ingredients: { "Chicken broth (g)": 200, "Rice (g)": 50, "Egg (g)": 50, "Lemon juice (g)": 30 } },
        { name: "Imam Bayildi", fiber: 6, calories: 240, protein: 5, sugar: 9, fat: 16, vitamins: 35, ingredients: { "Eggplant (g)": 200, "Onion (g)": 80, "Tomato (g)": 100, "Olive oil (g)": 25 } },
        { name: "Chicken Enchiladas (Mexican)", fiber: 5, calories: 420, protein: 30, sugar: 4, fat: 18, vitamins: 30, ingredients: { "Chicken (g)": 150, "Corn tortillas (g)": 80, "Enchilada sauce (g)": 80, "Cheese (g)": 30 } },
        { name: "Beef Barbacoa Tacos", fiber: 4, calories: 380, protein: 28, sugar: 2, fat: 20, vitamins: 20, ingredients: { "Beef (g)": 140, "Corn tortillas (g)": 60, "Onion (g)": 30, "Cilantro (g)": 10 } },
        { name: "Vegetarian Enchiladas", fiber: 8, calories: 360, protein: 12, sugar: 6, fat: 12, vitamins: 35, ingredients: { "Black beans (g)": 100, "Corn tortillas (g)": 80, "Enchilada sauce (g)": 80, "Spinach (g)": 60 } },
        { name: "Carnitas (Slow-cooked Pork) Tacos", fiber: 3, calories: 420, protein: 32, sugar: 1, fat: 24, vitamins: 15, ingredients: { "Pork (g)": 150, "Corn tortillas (g)": 60, "Onion (g)": 30 } },
        { name: "Chicken Fajitas", fiber: 5, calories: 360, protein: 32, sugar: 5, fat: 12, vitamins: 30, ingredients: { "Chicken (g)": 150, "Bell peppers (g)": 120, "Onion (g)": 60, "Tortilla (g)": 60 } },
        { name: "Steak Fajitas", fiber: 4, calories: 420, protein: 34, sugar: 4, fat: 18, vitamins: 25, ingredients: { "Steak (g)": 150, "Bell peppers (g)": 120, "Onion (g)": 60, "Tortilla (g)": 60 } },
        { name: "Shrimp Tacos (Cilantro Lime)", fiber: 3, calories: 300, protein: 26, sugar: 2, fat: 10, vitamins: 18, ingredients: { "Shrimp (g)": 140, "Corn tortillas (g)": 60, "Cabbage (g)": 50, "Lime (g)": 10 } },
        { name: "Bean and Cheese Burrito", fiber: 9, calories: 480, protein: 18, sugar: 6, fat: 18, vitamins: 25, ingredients: { "Flour tortilla (g)": 100, "Black beans (g)": 120, "Cheddar (g)": 40, "Rice (g)": 80 } },
        { name: "Grilled Fish Tacos (Mexican)", fiber: 4, calories: 340, protein: 28, sugar: 2, fat: 12, vitamins: 20, ingredients: { "White fish (g)": 140, "Corn tortillas (g)": 60, "Cabbage (g)": 50, "Lime (g)": 10 } },
        { name: "Chiles Rellenos (Cheese Stuffed)", fiber: 4, calories: 360, protein: 16, sugar: 5, fat: 20, vitamins: 30, ingredients: { "Poblano pepper (g)": 120, "Cheese (g)": 60, "Egg (g)": 50, "Tomato sauce (g)": 50 } },
        { name: "Quesadilla (Cheese & Veg)", fiber: 5, calories: 380, protein: 18, sugar: 3, fat: 20, vitamins: 20, ingredients: { "Flour tortilla (g)": 80, "Cheese (g)": 60, "Bell pepper (g)": 60, "Onion (g)": 30 } },
        { name: "Chicken Mole (Mexican)", fiber: 3, calories: 420, protein: 32, sugar: 6, fat: 18, vitamins: 25, ingredients: { "Chicken (g)": 150, "Mole sauce (g)": 90, "Rice (g)": 80 } },
        { name: "Pozole Roja (Pork Hominy Soup)", fiber: 6, calories: 380, protein: 28, sugar: 3, fat: 14, vitamins: 30, ingredients: { "Pork (g)": 120, "Hominy (g)": 120, "Chili (g)": 20, "Cabbage (g)": 50 } },
        { name: "Tamales (Chicken)", fiber: 4, calories: 360, protein: 20, sugar: 2, fat: 18, vitamins: 15, ingredients: { "Masa (g)": 100, "Chicken (g)": 80, "Masa wrapper (g)": 20, "Salsa (g)": 30 } },
        { name: "Elote - Mexican Street Corn", fiber: 3, calories: 210, protein: 6, sugar: 6, fat: 10, vitamins: 18, ingredients: { "Corn on cob (g)": 150, "Mayonnaise (g)": 15, "Cotija cheese (g)": 15, "Lime (g)": 10 } },
        { name: "Salsa Verde Chicken Bowl", fiber: 6, calories: 380, protein: 30, sugar: 4, fat: 12, vitamins: 30, ingredients: { "Chicken (g)": 140, "Brown rice (g)": 100, "Salsa verde (g)": 60, "Black beans (g)": 80 } },
        { name: "Pico de Gallo & Chips (Snack)", fiber: 4, calories: 200, protein: 3, sugar: 4, fat: 8, vitamins: 25, ingredients: { "Tomato (g)": 100, "Onion (g)": 30, "Cilantro (g)": 10, "Tortilla chips (g)": 40 } },
        { name: "Carne Asada with Rice", fiber: 4, calories: 450, protein: 36, sugar: 2, fat: 22, vitamins: 20, ingredients: { "Steak (g)": 170, "Rice (g)": 120, "Grilled onion (g)": 40 } },
        { name: "Chilaquiles (Breakfast)", fiber: 5, calories: 420, protein: 18, sugar: 5, fat: 22, vitamins: 25, ingredients: { "Tortilla chips (g)": 80, "Green/Red salsa (g)": 100, "Egg (g)": 60, "Cheese (g)": 30 } },
        { name: "Mexican Black Bean Soup", fiber: 10, calories: 320, protein: 16, sugar: 4, fat: 6, vitamins: 35, ingredients: { "Black beans (g)": 180, "Tomato (g)": 80, "Onion (g)": 50, "Cumin (g)": 5 } }
]
